name: Load BigQuery data

on:
  workflow_dispatch:
  push:
    branches:
      - jdb/2025-12-automate-bigquery-loading

permissions: {}

jobs:
  load:
    if: github.repository == 'grafana/grafana-pathfinder-app'
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Get GCP secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@28361cdb22223e5f1e34358c86c20908e7248760 # v1.1.0
        with:
          repo_secrets: |
            SERVICE_ACCOUNT_JSON=pathfinder-bigquery-service-account:'credentials.json'

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ env.SERVICE_ACCOUNT_JSON }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Update `make docs` procedure
        run: ./scripts/load-bigquery.bash update
        shell: bash
