name: Load BigQuery data

on:
  workflow_dispatch:

permissions: {}

jobs:
  load:
    if: github.repository == 'grafana/grafana-pathfinder-app'
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Get GCP secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@28361cdb22223e5f1e34358c86c20908e7248760 # v1.1.0
        with:
          repo_secrets: |
            SERVICE_ACCOUNT_JSON=pathfinder-bigquery-service-account:'credentials.json'

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ env.SERVICE_ACCOUNT_JSON }}

      - name: Load data
        run: ./scripts/load-bigquery.bash update
        shell: bash
